pin prettier version because of breaking changes
Suddenly, the prettier action started to fail for no aparent reason.
The error message was:

```
Installing prettier...
Checking plugin: prettier-plugin-solidity
Prettifying files...
Files:
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/archive/PersonalInviteOld.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/archive/PersonalInviteOld.t.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/AllowList.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/ContinuousFundraising.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/FeeSettings.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/interfaces/IFeeSettings.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/PersonalInvite.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/PersonalInviteFactory.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/Token.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/contracts/VestingWalletFactory.sol".
docs/deployment.md 59ms
docs/dev_overview.md 33ms
docs/fees.md 27ms
docs/npm_publishing.md 7ms
docs/price.md 31ms
docs/specification.md 114ms
docs/testing.md 15ms
docs/user_overview.md 45ms
docs/using_the_contracts.md 51ms
LICENSE.md 186ms
README.md 45ms
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/script/CheckToken.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/script/DeployCompany.sol".
Error:  No parser could be inferred for file "/home/runner/work/tokenize.it-smart-contracts/tokenize.it-smart-contracts/script/DeployPlatform.s.sol".
script/hardhatVerifyConstructorArguments/ContinuousFundraising.js 52ms
script/hardhatVerifyConstructorArguments/TokenGoerli.js 3ms
script/hardhatVerifyConstructorArguments/TokenMainnet.js 2ms
script/hardhatVerifyConstructorArguments/VestingWallet.js 3ms
```

It appears prettier v3 introduces some breaking changes, so I pinned
version 2.8.8. See https://github.com/creyD/prettier_action/issues/124